import logo from '../assets/logo.png'

export const footer = () => {

    const footerLinks = [
        {text: "Humans in Space", href: "https://science.nasa.gov/humans-in-space"}, 
        {text: "Earth", href: "https://science.nasa.gov/earth"},
        {text: "The Solar System", href: "https://science.nasa.gov/solar-system"},
        {text: "The Universe", href: "https://science.nasa.gov/universe"}, 
        {text: "Science", href: "https://science.nasa.gov"}
    ]

    const footer = document.createElement("footer")
        const copyrightWrapper = document.createElement("div")
        copyrightWrapper.classList.add("copyright-wrapper")
            
            const footerTitleArea = document.createElement("div")
            footerTitleArea.classList.add("footer-title-area")
                const footerTitle = document.createElement("h3")
                footerTitle.textContent = "Worshipers of Jupiter"
                const copyright = document.createElement("p")
                copyright.classList.add("bodyS")
                copyright.textContent = "© 2025 Worshipers of Jupiter · All Rights Reserved"
            
            const footerLogoWrapper = document.createElement("div")
            footerLogoWrapper.classList.add("footer-logo-wrapper")
                const footerLogo = document.createElement("img")
                footerLogo.src = logo
        
        const infoWrapper = document.createElement("div")
        infoWrapper.classList.add("info-wrapper")
            
            const infoLinksWrapper = document.createElement("div")
            infoLinksWrapper.classList.add("info-links-wrapper")

                const infoLinksTitle = document.createElement("h4")
                infoLinksTitle.textContent = "NASA"

                const infoLinks = document.createElement("ul")
                infoLinks.classList.add("info-links")

                    footerLinks.forEach(link => {
                        const footerLinkWrapper = document.createElement("li")
                        footerLinkWrapper.classList.add("no-glow")
                        footerLinkWrapper.classList.add("footer-link-wrapper")
                            const footerLink = document.createElement("a")
                            footerLink.classList.add("text-left-aligned")
                            footerLink.textContent = link.text
                            footerLink.href = link.href

                            footerLinkWrapper.append(footerLink)
                            infoLinks.append(footerLinkWrapper)
                            infoLinksWrapper.append(infoLinksTitle, infoLinks)
                    })
            
            const disclaimerWrapper = document.createElement("div")
            disclaimerWrapper.classList.add("disclaimer-wrapper")
                
                const disclaimerTitle = document.createElement("h4")
                disclaimerTitle.textContent = "DISCLAIMERS"
                disclaimerTitle.classList.add("text-left-aligned")

                const imagesDisclaimer = document.createElement("p")
                imagesDisclaimer.classList.add("bodyS")
                imagesDisclaimer.classList.add("text-left-aligned")
                imagesDisclaimer.textContent = "Some images generated by AI"

                const informationDisclaimer = document.createElement("p")
                informationDisclaimer.classList.add("bodyS")
                informationDisclaimer.classList.add("text-left-aligned")
                informationDisclaimer.textContent = "Some information generated by AI"


    disclaimerWrapper.append(disclaimerTitle, imagesDisclaimer, informationDisclaimer)    
    infoWrapper.append(infoLinksWrapper, disclaimerWrapper)
    footerLogoWrapper.append(footerLogo)
    footerTitleArea.append(footerTitle, copyright)
    copyrightWrapper.append(footerTitleArea, footerLogoWrapper)
    footer.append(copyrightWrapper, infoWrapper)

    return footer
}